// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NycCodeCamp.MonoTouchApp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SpeakerViewController")]
	public partial class SpeakerViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_SpeakerBio;
		
		private MonoTouch.UIKit.UILabel __mt_SpeakerName;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("SpeakerBio")]
		private MonoTouch.UIKit.UILabel SpeakerBio {
			get {
				this.__mt_SpeakerBio = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("SpeakerBio")));
				return this.__mt_SpeakerBio;
			}
			set {
				this.__mt_SpeakerBio = value;
				this.SetNativeField("SpeakerBio", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("SpeakerName")]
		private MonoTouch.UIKit.UILabel SpeakerName {
			get {
				this.__mt_SpeakerName = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("SpeakerName")));
				return this.__mt_SpeakerName;
			}
			set {
				this.__mt_SpeakerName = value;
				this.SetNativeField("SpeakerName", value);
			}
		}
	}
}
