//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NycCodeCamp.MonoAndroidApp
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Email = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Overview = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Rooms = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Schedule = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Speakers = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Sponsors = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Tags = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Update = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Web = 2130837513;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int Abstract = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int Bio = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int Description = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int Email = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int MapImage = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int Overview = 2131099664;
			
			// aapt resource value: 0x7f060003
			public const int Room = 2131099651;
			
			// aapt resource value: 0x7f060011
			public const int Rooms = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int Sessions = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int Slots = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int SpeakerName = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int Speakers = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int SponsorName = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int Sponsors = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int TagName = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int Tags = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int Time = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int Title = 2131099649;
			
			// aapt resource value: 0x7f06000f
			public const int Update = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int Web = 2131099667;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Overview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int OverviewItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OverviewSectionHeader = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Rooms = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Session = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Sessions = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SessionsByTag = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SessionsByTagItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SessionsItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SessionsSectionHeader = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Speaker = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Speakers = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SpeakersItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Sponsor = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Sponsors = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SponsorsItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SponsorsSectionHeader = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Tags = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int TagsItem = 2130903058;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainOptionsMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int SpeakerOptionsMenu = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int SponsorOptionsMenu = 2131034114;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			private String()
			{
			}
		}
	}
}
