//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NycCodeCamp.MonoAndroidApp
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int SectionHeader = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int WindowTitleBackground = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Email = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ListSelector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ListSelectorFocusedPressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Overview = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Rooms = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Schedule = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Speakers = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Sponsors = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Tags = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Update = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Web = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int WindowBackground = 2130837517;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int Abstract = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int Bio = 2131230731;
			
			// aapt resource value: 0x7f080007
			public const int Description = 2131230727;
			
			// aapt resource value: 0x7f080013
			public const int Email = 2131230739;
			
			// aapt resource value: 0x7f080004
			public const int MapImage = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int Name = 2131230726;
			
			// aapt resource value: 0x7f080012
			public const int Overview = 2131230738;
			
			// aapt resource value: 0x7f080003
			public const int Room = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int Rooms = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int Sessions = 2131230730;
			
			// aapt resource value: 0x7f080000
			public const int Slots = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int SpeakerName = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public const int Speakers = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int SponsorName = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int Sponsors = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int TagName = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int Tags = 2131230735;
			
			// aapt resource value: 0x7f080008
			public const int Time = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int Title = 2131230721;
			
			// aapt resource value: 0x7f080011
			public const int Update = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int Web = 2131230740;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Overview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int OverviewItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Room = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Rooms = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RoomsItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SectionHeader = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Session = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Sessions = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SessionsByTag = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SessionsByTagItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SessionsItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Speaker = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Speakers = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SpeakersItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Sponsor = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Sponsors = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SponsorsItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Tags = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int TagsItem = 2130903058;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int MainOptionsMenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int SpeakerOptionsMenu = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int SponsorOptionsMenu = 2131165186;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationTheme = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int DetailSubtitle = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int DetailText = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int DetailTitle = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int ListItemSubtitle = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int ListItemTitle = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int ListView = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int SectionHeader = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int SessionDetails = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int WindowTitleBackground = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Wrapper = 2131099651;
			
			private Style()
			{
			}
		}
	}
}
