// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NycCodeCamp.MonoTouchApp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SponsorViewController")]
	public partial class SponsorViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_SponsorName;
		
		private MonoTouch.UIKit.UIScrollView __mt_Scroller;
		
		private MonoTouch.UIKit.UILabel __mt_Description;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("SponsorName")]
		private MonoTouch.UIKit.UILabel SponsorName {
			get {
				this.__mt_SponsorName = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("SponsorName")));
				return this.__mt_SponsorName;
			}
			set {
				this.__mt_SponsorName = value;
				this.SetNativeField("SponsorName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("Scroller")]
		private MonoTouch.UIKit.UIScrollView Scroller {
			get {
				this.__mt_Scroller = ((MonoTouch.UIKit.UIScrollView)(this.GetNativeField("Scroller")));
				return this.__mt_Scroller;
			}
			set {
				this.__mt_Scroller = value;
				this.SetNativeField("Scroller", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("Description")]
		private MonoTouch.UIKit.UILabel Description {
			get {
				this.__mt_Description = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("Description")));
				return this.__mt_Description;
			}
			set {
				this.__mt_Description = value;
				this.SetNativeField("Description", value);
			}
		}
	}
}
